### ISSUE TITLE
Limit NotificationBadge shape to circle

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#159]
According to Orbit, this version should be only circular.

**Comment by username0x0a** [comment]
What are we supposed to use instead when having more than displayable count of notifications? 🤔 In that case, I really hope that for Notifications badge, we don't actually use `NotificationBadge`. 🙃 That sounds like a really unexpected design.

**Comment by sjavora** [comment]
A good question to ask the Orbit team. I'd guess at some point you will just use some icon.

**Comment by hrach** [comment]
NotificationBadge is deprecated and replaced by circled Badge.

**Comment by sjavora** [comment]
Citation needed.
