### ISSUE TITLE
Make wrapping components respect common modifiers

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#181]
For better flexibility and composability, wrapping components like `Card`, `Tile` etc. should respect some common modifiers for their sub-components, that might be used to override their default behaviour:

- `foregroundColor`
- `tint`
- `lineLimit`?

**Comment by sjavora** [comment]
How would `foregroundColor` work? It's not exposed through the environment AFAIK. `lineLimit` is also mentioned in #173

**Comment by PavelHolec** [comment]
> How would `foregroundColor` work? It's not exposed through the environment AFAIK. `lineLimit` is also mentioned in #173

👍  `foregroundColor` probably wont make sense anyway as these wrapping components often use multiple colors. Moved `tint` to the other issue, closing this one
