### ISSUE TITLE
SecureTextField shows runtime warnings

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#216]
Appears after successful login using the InputField.

<img width="996" alt="image (1)" src="https://user-images.githubusercontent.com/35844477/176474545-a2e3ae27-f763-44f9-88a5-28edcc5d26a9.png">

**Comment by Parabak** [comment]
Warning is happening when View is updating (e.g. VM is changed) while Keyboard is a first responder. More reliable fix is to dismiss keyboard before updating the View.       

Alternative is to wrap `isEditing = ` in `DispatchQueue.main.async {}`. This solves issue in this particular case, but warning might appear in the other place.
