### ISSUE TITLE
Try to integrate SwiftFormat as a build plugin

### ISSUE THREAD

**Issue by sjavora** [kiwicom/orbit-swiftui#236]

**Comment by Parabak** [comment]
Also check the rule to insert a new line after type declaration. Now sure about `enum case` though
https://github.com/kiwicom/orbit-swiftui/pull/234#discussion_r927435549

**Comment by sjavora** [comment]
Meh, it seems build plugins currently simply [cannot write to the package directory at all](https://forums.swift.org/t/is-it-possible-to-set-a-flag-or-an-option-to-allow-plugin-to-write-to-a-package-directory-subdirectories/56166/5) and we'd have to use a command plugin, which means invoking it manually 😞

**Comment by sjavora** [comment]
I guess we could do SwiftLInt instead, but only for generating warnings, no corrections.
