### ISSUE TITLE
Add DynamicTypeSize support to Timeline

### ISSUE THREAD

**Issue by Parabak** [kiwicom/orbit-swiftui#241]
In case issue #195 will be merged, main issue to fully support DynamicTypeSize  will be to find where exactly the icon is located.  
The icon might be aligned either to a first text line or to the container top.
Icon size is a dynamic value, while in timeline we use a constant

Also we should expose init with **both custom header and content** so user will be more flexible with desired design.  As an example, now horisontal padding is hardcoded which leads to a bigger gap, when  custom header is used instead of badge component.

**Comment by PavelHolec** [comment]
Basic fixes were done as part of #315
