### ISSUE TITLE
Use list of available Illustrations for update script 

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#258]
This list can be used to drive the update_illustrations scripts to be sure we download all available illustrations, instead of adding them manually.

https://github.com/kiwicom/orbit-compose/blob/3f549b8f7ad052033d4616414845e3536a82c2f7/generator/src/main/java/kiwi/orbit/compose/generator/illustrations/Main.kt#L15

**Comment by sjavora** [comment]
Closed in favor of #341
