### ISSUE TITLE
Unable to render flattened version of PlatformViewRepresentableAdaptor<SelectableLabelWrapper>

### ISSUE THREAD

**Issue by sjavora** [kiwicom/orbit-swiftui#274]
When using `.elevation` on a view that contains a selectable `Text`, the following message is printed in the console:

```
Unable to render flattened version of PlatformViewRepresentableAdaptor<SelectableLabelWrapper>
```

When stripped down to a minimum example, the text shows some debug appearance from SwiftUI:
```swift
Text("teest", isSelectable: true)
    .elevation(.level1)
```
produces
<img width="43" alt="Screenshot 2022-08-17 at 18 52 12" src="https://user-images.githubusercontent.com/12349477/185197624-75861eb5-4b3d-479b-82d2-1200740b3625.png">

**Comment by PavelHolec** [comment]
It is probably an expected warning. Solution is to either

- Expose "live" elevation as available for caller to use the version without `drawingGroup`
- Use simple rounded shape for surface in case of `prerender` version, instead of using the original content as a background

**Comment by sjavora** [comment]
This is causing some really wild things in UI tests now...

![testPersonalDetailsScreen-1 1](https://user-images.githubusercontent.com/12349477/186269351-77b20ce8-05a9-41e5-8d35-d9256dbffbd6.png)
