### ISSUE TITLE
Should `Select` use `.accessibility(.inputValue)`?

### ISSUE THREAD

**Issue by sjavora** [kiwicom/orbit-swiftui#301]
While writing some page objects for UI tests, I noticed that `Select` uses `.accessibility(.inputValue)`... but `Select` is not an input... is this a copy/paste error is it intended? I'd create `.selectValue` rather than reuse `.inputValue`...

cc @PavelHolec

**Comment by PavelHolec** [comment]
👍 That or maybe even `.value`?

**Comment by PavelHolec** [comment]
Fixed by #355
