### ISSUE TITLE
Rename previews to be more helpful in Xcode 14

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#307]
As previews changed in Xcode 14, there should be a different naming convention.

#### Current

<img width="726" alt="image" src="https://user-images.githubusercontent.com/35844477/190999269-e2ced7f7-8abc-4a30-b938-ffd6c6b9385e.png">

**Comment by sjavora** [comment]
I noticed this too, but doesn't it depend on `.previewName(`?

**Comment by PavelHolec** [comment]
> I noticed this too, but doesn't it depend on `.previewName(`?

Yes. We should probably fill it manually for each preview so the labels are more informative.
