### ISSUE TITLE
Enhance relevant inits with binding parameter

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#399]
Some components might need to use both initializers:
- with a simple property and callback (when the selection needs to be injected with custom logic)
- with a binding (when the selection should match 1:1 in both directions)

Example is the native `DisclosureGroup` component that as an additional initializer that takes binding: 

> This initializer also let you set or read the expanded state programmatically.

Components:
- `Tag`
- `Collapse`
- `Checkbox`
- `Radio`
- `Switch`
- TBD...

**Comment by sjavora** [comment]
@PavelHolec Is there a native component that also has the callback? I'm looking at Orbit's `Checkbox` and can't imagine a scenario right now where we would prefer the action callback to a binding. No usage like that seems to exist in the app.

**Comment by sjavora** [comment]
In fact, out of SwiftUI's native controls with togglable states, they all offer a binding and there is only one that also has a coustom init with callbacks - this [`Stepper` one](https://developer.apple.com/documentation/swiftui/stepper/init(label:onincrement:ondecrement:oneditingchanged:)) - we could add something like that if really needed, but it doesn't seem to me like we actually need callbacks as standard.
