### ISSUE TITLE
Pass `TextLink` action as an environment value

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#506]
To fix various `TextLink` issues (missing implementation for `Text` concatenation) and simplify the API, the TextLink action can be done in a similar way as the [native](https://developer.apple.com/documentation/swiftui/environmentvalues/refresh) `refresh()` action - passing the action handler via environment value instead.

This will extract the action handling out of the components themselves and any `Text` in any component would gain the ability to have `TextLink`s.

Ie., instead of explicitly propagating the action in every component:

```
Alert(
  ...
 descriptionTextLinkAction: ..
) {
    Text(..., textLinkAction: ...)
}
```

A call site would be able to specify the link action for any subtree, like:

```
Alert(
  ...
) {
    Text(...)
}
.textLinkAction { _ in
    ... // will be called by any text inside the hierarchy that will detect the TextLink tap
}
```

**Comment by sjavora** [comment]
Damnit, I was about to suggest this any day now 😀

**Comment by PavelHolec** [comment]
> Damnit, I was about to suggest this any day now 😀

It looks pretty promising - the API is so much more lightweight now. This shows how the SwiftUI environment parameter inheritance is superior over the rigid initializer parameters (similar principle may apply to any dependencies)
