### ISSUE TITLE
Update `Alert` design

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#533]
- Smaller spacing between buttons (8pt)
- Smaller corner radius for buttons (3pt)
- Use “ButtonLink” for action in Inline variant

The Alert buttons API should be updated as well to remove the awkward enum with associated action handlers

#### Option 1
They may need to be extracted to internal components (`AlertButton`).
The Buttons API could be improved to take a ResultBuilder of Up to these new 2 `AlertButton` components, instead of passing cumbersome parameters.

#### Option 2
The Alert would take action closures for each button and based on their non-nil values, internal buttons would be automatically constructed.

The init taking only one action handler would have `isInline: Bool = false` parameter, while the one with two action handlers would be automatically non-inline.

```
Alert(...) {
    // primary (or single) button action
} secondaryAction: {
    // secondary action
} icon: {
    CountryFlag(..)
}

Alert(..., isInline: true) {
    // primary (single) button action
}
```

For the corner radius of buttons, it might be useful if we fully extract our button as a `buttonStyle` (it partially is) with configurable corner radius (automatic radius is supported only in iOS16+) so that we can use Native `SwiftUI.Button` with this styling override in case of Alert.

Background color from normal colors:
- BG opacity: 12%
- BG opacity: 24%

Text color:
- Default: Dark
- Active: Dark :active

<img width="627" alt="image" src="https://user-images.githubusercontent.com/35844477/232519026-64b349cd-ab48-480c-8069-bc646d2a5474.png">

**Comment by sjavora** [comment]
> Smaller corner radius for buttons (3pt)

@PavelHolec should this apply to all buttons or do we need to copy/paste them here? I guess that's what

> The Alert buttons may need to be extracted to internal components.

means?

**Comment by sjavora** [comment]
**Option 2** from the description is not really an option since we need to specify the button titles, btw.
