### ISSUE TITLE
Update `Badge` design

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#534]
- Remove border for light variants
- Allow leading and trailing icons

<img width="157" alt="image" src="https://user-images.githubusercontent.com/35844477/231381058-43599fb2-3453-4140-b199-2677f018591a.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/35844477/231377981-0544a213-202d-4947-bdc2-f54c5477f245.png">

**Comment by sjavora** [comment]
@PavelHolec where is the leading/trailing icon version from? I can only see the text OR icon versions in figma at https://www.figma.com/file/YMfJkmUMV8xiY7fgeW6QAr/%5BOrbit%5D-Native-Components?type=design&node-id=468-801&t=YZ10OTk30SNzpZCQ-0

**Comment by PavelHolec** [comment]
> @PavelHolec where is the leading/trailing icon version from? I can only see the text OR icon versions in figma at https://www.figma.com/file/YMfJkmUMV8xiY7fgeW6QAr/%5BOrbit%5D-Native-Components?type=design&node-id=468-801&t=YZ10OTk30SNzpZCQ-0

It is taken from the component. New figma component composition has a tradeoff in terms of visibility for devs - it does not show all variants/combinations - it needs to be used in a draft for example, to be able to explore all options.

<img width="674" alt="image" src="https://github.com/kiwicom/orbit-swiftui/assets/35844477/5e3d26c9-a820-4489-9950-460e327bf84a">

**Comment by sjavora** [comment]
Done in #525.
