### ISSUE TITLE
Icons are not encoding properly

### ISSUE THREAD

**Issue by matthewnaples** [kiwicom/orbit-swiftui#646]
Hello, when I run the storybook in the simulator (haven't checked on device), the icons don't seem to be encoded properly. This also happens when I attempt to use the icons in another project. 
![Simulator Screenshot - iPhone 14 Pro - 2023-08-11 at 10 44 39](https://github.com/kiwicom/orbit-swiftui/assets/50719340/d014476a-94e6-4e0e-a7e0-bac7ad2bf2a2)

Is there something I need to update on my end to make sure they encode properly? Thanks!

**Comment by PavelHolec** [comment]
Hello, 
For Orbit icons to work, it is required to call `Font.registerOrbitFonts()` anytime on the app start (or SwiftUI preview) once.

The following tutorial covers this part with the optional custom fonts used for Orbit text components.

https://kiwicom.github.io/orbit-swiftui/tutorials/orbit/01-01-hello_orbit

**Comment by cameroncooke** [comment]
Just to add to this, while this is correct the documentation also states:

> If you omit this optional step, Orbit components will use default iOS system fonts.

If you're not licensed to use this font and would like to use custom or the system fonts you also don't get the icons as they are loaded as a font as part of the `registerOrbitFonts()` call.

How does one use default fonts and continue to use the bundled icons?

**Comment by cameroncooke** [comment]
I managed to work around this by manually calling:

```swift
        if let iconsFontURL = Bundle.orbit.url(forResource: "Icons.ttf", withExtension: nil) {
            _ = Font.registerFont(at: iconsFontURL)
        }
```

But I think it would help if the loading of the icons was decoupled from the loading of the licensed fonts.
