### ISSUE TITLE
Update `Alert` button background color to match design

### ISSUE THREAD

**Issue by sjavora** [kiwicom/orbit-swiftui#696]
| figma | reality |
| ----- | ------|
| ![screenshot_2023-10-17_at_13 54 44_720](https://github.com/kiwicom/orbit-swiftui/assets/12349477/1f2735ff-f82d-4dd9-98b4-03d372fe46ca) | ![screenshot_2023-10-17_at_13 57 38_480](https://github.com/kiwicom/orbit-swiftui/assets/12349477/d59e6a53-44ab-4eb1-885f-26b68996beb1) |

**Comment by PavelHolec** [comment]
Answer from Orbit is that this is not an issue for now. Ideally, colors would not be driven by opacity.
