### ISSUE TITLE
Deprecate methods for iOS15

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#717]
Some methods can be now deprecated in favor of native version.

```
@available(iOS, deprecated: 15.0, renamed: "focused(_:)")
func inputFieldFocus
func inputFieldBeginEditingAction
func inputFieldEndEditingAction
```

Other input field related methods cannot be replaced with native version, as those only work for the native `TextField`:

**Comment by sjavora** [comment]
@PavelHolec since we're on this subject, can we also mark our focus handling as deprecated on iOS 15?
