### ISSUE TITLE
Create `SegmentedSwitch` component

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#77]
Can be probably created by mimicking or reusing parts of Tabs/Tab component or the native SegmentedControl.

https://www.figma.com/file/YMfJkmUMV8xiY7fgeW6QAr/%5BOrbit%5D-Native-Components?node-id=7798%3A3188

**Comment by sjavora** [comment]
@Parabak this issue wasn't closed because you need to write exactly "Closes #77" or "Resolves #77" - those worked for me, anyway.

Closing this one manually.
