### ISSUE TITLE
Support async calls in interactive elements with task parameter

### ISSUE THREAD

**Issue by PavelHolec** [kiwicom/orbit-swiftui#84]
First we need to check if it is compatible with native SwiftUI API. Maybe we missed something.
But it seems this would make the syntax easier for concurrency-enabled code.

It should be enough to replace action with `task` as an async variant of action. Async functions are a subtype of non-async (same as throws), so if we just add async to action, it should "just work" with the simple syntax:

![](https://gitlab.skypicker.com/mobile/ios/uploads/f327629e01e22f0515108dcfafe8c508/Screenshot_2022-03-31_at_12.30.28.png)

**Comment by sjavora** [comment]
I'm no longer sure this is a good idea... it would mean that even synchronous calls would become asynchronous because of being enqueued inside a `Task` - let's leave this explicit.
