### ISSUE TITLE
`TextLink`s disappear when app resigns active

### ISSUE THREAD

**Issue by sjavora** [kiwicom/orbit-swiftui#853]
This is due to `redactionReasons` getting set to `.privacy` by iOS.

I doubt we want to actually set the text color to `.clear` in this case. It looks bad in the app and the native link support in `SwftIUI.Text` doesn't do it. Compare Orbit `Text` (top, green) with SwiftUI `Text` (bottom, red).

https://github.com/user-attachments/assets/2cb69bff-104e-4014-810f-2dd06e791ed2

**Comment by PavelHolec** [comment]
Side effect of #788
